import {
  logout,
  changeEmail,
  checkEmail,
  changePassword,
  checkPassword,
  showRegistrationForm,
  changePasswordDuplicate,
  checkPasswordDuplicate,
  changeName,
  checkName,
  authorize,
  registrate,
  toggleUserFotoForm,
  changeUserFoto,
  saveUserFoto
} from './authorization';

import {
  getProjectList,
  changeProjectName,
  checkProjectName,
  changeProjectDescription,
  saveProject,
  toggleProjectForm,
  editProject,
  deleteProject,
  selectProject,
  getProjectWithTasks,
  backToTheProjectList,
  toggleDeleteProjectForm,
  changeSorting
} from './project';

import {
  toggleTaskForm,
  changeTaskDescription,
  checkTaskDescription,
  saveTask,
  changeTask,
  deleteTask,
  changeTaskStatus,
  toggleDeleteTaskForm,
  changeExecutorName,
  changePriority
} from './task';

import {
  toggleUserForm,
  changeUserEmail,
  checkUserEmail,
  saveUser,
  toggleDeleteUserForm,
  deleteUser,
  inviteNewUser
} from './team';

export {
  logout,
  changeEmail,
  checkEmail,
  changePassword,
  checkPassword,
  showRegistrationForm,
  changePasswordDuplicate,
  checkPasswordDuplicate,
  changeName,
  checkName,
  authorize,
  registrate,
  toggleUserFotoForm,
  changeUserFoto,
  saveUserFoto,
  getProjectList,
  changeProjectName,
  checkProjectName,
  changeProjectDescription,
  saveProject,
  toggleProjectForm,
  editProject,
  deleteProject,
  selectProject,
  getProjectWithTasks,
  toggleTaskForm,
  changeTaskDescription,
  checkTaskDescription,
  saveTask,
  changeTask,
  deleteTask,
  changeTaskStatus,
  backToTheProjectList,
  toggleDeleteProjectForm,
  toggleDeleteTaskForm,
  toggleUserForm,
  changeUserEmail,
  checkUserEmail,
  saveUser,
  toggleDeleteUserForm,
  deleteUser,
  inviteNewUser,
  changeExecutorName,
  changeSorting,
  changePriority
};
