const authConstants = [
  'LOG_OUT',
  'CHANGE_EMAIL',
  'CHECK_EMAIL',
  'CHANGE_PASSWORD',
  'CHECK_PASSWORD',
  'SHOW_REGISTRATION_FORM',
  'CHANGE_PASSWORD_DUPLICATE',
  'CHECK_PASSWORD_DUPLICATE',
  'CHANGE_NAME',
  'CHECK_NAME',
  'VALIDATE_AUTHORIZATION_FORM',
  'VALIDATE_REGISTRATION_FORM',
  'AUTHORIZATION_REQUEST',
  'AUTHORIZATION_SUCCESS',
  'AUTHORIZATION_FAILURE',
  'REGISTRATION_REQUEST',
  'REGISTRATION_SUCCESS',
  'REGISTRATION_FAILURE',
  'TOGGLE_USER_PHOTO_FORM',
  'CHANGE_USER_PHOTO',
  'SAVE_USER_PHOTO',
  'USER_ALREADY_EXIST',
  'TOGGLE_LOGIN_FORM',
  'GET_INFO'
];

export default authConstants;
