import tokeys from 'tokeys';

export default tokeys([
  'CHANGE_EMAIL',
  'CHECK_EMAIL',
  'CHANGE_PASSWORD',
  'CHECK_PASSWORD',
  'SHOW_REGISTRATION_FORM',
  'CHANGE_PASSWORD_DUPLICATE',
  'CHECK_PASSWORD_DUPLICATE',
  'CHANGE_NAME',
  'CHECK_NAME',
  'VALIDATE_AUTHORIZATION_FORM',
  'VALIDATE_REGISTRATION_FORM',
  'AUTHORIZATION_REQUEST',
  'AUTHORIZATION_SUCCESS',
  'AUTHORIZATION_FAILURE'
])
