const projectConstants = [
  'PROJECT_LIST',
  'CHANGE_PROJECT_NAME',
  'CHECK_PROJECT_NAME',
  'CHANGE_PROJECT_DESCRIPTION',
  'VALIDATE_PROJECT',
  'SAVE_PROJECT',
  'TOGGLE_PROJECT_FORM',
  'EDIT_PROJECT',
  'DELETE_PROJECT',
  'SELECT_PROJECT',
  'GET_PROJECT_WITH_TASKS',
  'BACK_TO_THE_PROJECT_LIST',
  'TOGGLE_DELETE_PROJECT_FORM'
];

export default projectConstants;
